# 工作流名称
name: Sync-Images-to-Aliyun-Mirrors
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to Aliyun Mirrors.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Aliyun Mirrors
      uses: docker/login-action@v2.2.0
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Aliyun Mirrors
      run: |
        #!/usr/bin/env bash
        skopeo copy docker://docker.io/jenkins/jenkins:2.466-jdk21 docker://registry.cn-hangzhou.aliyuncs.com/aishinye/jenkins:2.466-jdk21
                                                      
                                                      
                                                      
 
